// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'boutiques_response.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$BoutiquesResponseImpl _$$BoutiquesResponseImplFromJson(
        Map<String, dynamic> json) =>
    _$BoutiquesResponseImpl(
      id: json['id'] as int?,
      title: json['title'] as String?,
      address: json['address'] as String?,
      fullAddress: json['full_address'] as String?,
      workingHours: json['working_hours'] as String?,
      images:
          (json['images'] as List<dynamic>?)?.map((e) => e as String).toList(),
      productCategories: json['product_categories'] as String?,
      productCategoriesBrend: json['product_categories_brend'] as String?,
      butterflies: json['butterflies'] as String?,
      balaclavas: json['balaclavas'] as String?,
      balletFlats: json['ballet_flats'] as String?,
      balmsRestorersSkin: json['balms_restorers_skin'] as String?,
      baseballCaps: json['baseball_caps'] as String?,
      bermuda: json['bermuda'] as String?,
      bikinis: json['bikinis'] as String?,
      blouses: json['blouses'] as String?,
      body: json['body'] as String?,
      bodyUnderwear: json['body_underwear'] as String?,
      sandals: json['sandals'] as String?,
      ankleBoots: json['ankle_boots'] as String?,
      boots: json['boots'] as String?,
      bra: json['bra'] as String?,
      bracelets: json['bracelets'] as String?,
      keyRings: json['key_rings'] as String?,
      briefcases: json['briefcases'] as String?,
      brooches: json['brooches'] as String?,
      trousers: json['trousers'] as String?,
      bras: json['bras'] as String?,
      value1: json['value_1'] as String?,
      value2: json['value_2'] as String?,
      value3: json['value_3'] as String?,
      value4: json['value_4'] as String?,
      value5: json['value_5'] as String?,
      value6: json['value_6'] as String?,
      value7: json['value_7'] as String?,
      value8: json['value_8'] as String?,
      value9: json['value_9'] as String?,
      value10: json['value_10'] as String?,
      value11: json['value_11'] as String?,
      value12: json['value_12'] as String?,
      value13: json['value_13'] as String?,
      value14: json['value_14'] as String?,
      value15: json['value_15'] as String?,
      value16: json['value_16'] as String?,
      value17: json['value_17'] as String?,
      value18: json['value_18'] as String?,
    );

Map<String, dynamic> _$$BoutiquesResponseImplToJson(
        _$BoutiquesResponseImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'title': instance.title,
      'address': instance.address,
      'full_address': instance.fullAddress,
      'working_hours': instance.workingHours,
      'images': instance.images,
      'product_categories': instance.productCategories,
      'product_categories_brend': instance.productCategoriesBrend,
      'butterflies': instance.butterflies,
      'balaclavas': instance.balaclavas,
      'ballet_flats': instance.balletFlats,
      'balms_restorers_skin': instance.balmsRestorersSkin,
      'baseball_caps': instance.baseballCaps,
      'bermuda': instance.bermuda,
      'bikinis': instance.bikinis,
      'blouses': instance.blouses,
      'body': instance.body,
      'body_underwear': instance.bodyUnderwear,
      'sandals': instance.sandals,
      'ankle_boots': instance.ankleBoots,
      'boots': instance.boots,
      'bra': instance.bra,
      'bracelets': instance.bracelets,
      'key_rings': instance.keyRings,
      'briefcases': instance.briefcases,
      'brooches': instance.brooches,
      'trousers': instance.trousers,
      'bras': instance.bras,
      'value_1': instance.value1,
      'value_2': instance.value2,
      'value_3': instance.value3,
      'value_4': instance.value4,
      'value_5': instance.value5,
      'value_6': instance.value6,
      'value_7': instance.value7,
      'value_8': instance.value8,
      'value_9': instance.value9,
      'value_10': instance.value10,
      'value_11': instance.value11,
      'value_12': instance.value12,
      'value_13': instance.value13,
      'value_14': instance.value14,
      'value_15': instance.value15,
      'value_16': instance.value16,
      'value_17': instance.value17,
      'value_18': instance.value18,
    };
