name: shared
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  intl: ^0.18.1
  device_info_plus: ^9.1.0
  hive: ^2.2.3
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  repositories:
    path: ../repositories
  models:
    path: ../models
  ui_kit:
    path: ../ui_kit

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
