name: blind_chicken
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.75+1

environment:
  sdk: '>=3.0.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.3

  #https://pub.dev/packages/auto_route
  auto_route: ^9.2.2
  #https://pub.dev/packages/cached_network_image
  cached_network_image: ^3.4.1
  #https://pub.dev/packages/cupertino_icons
  cupertino_icons: ^1.0.8
  #https://pub.dev/packages/get_it
  get_it: ^7.1.4
  #https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^8.1.6
  #https://pub.dev/packages/flutter_svg
  flutter_svg: ^2.0.10+1
  #https://pub.dev/packages/mask_text_input_formatter
  mask_text_input_formatter: ^2.9.0

  #https://pub.dev/packages/syncfusion_flutter_core
  syncfusion_flutter_core: ^26.2.14
  #https://pub.dev/packages/syncfusion_flutter_pdfviewer
  syncfusion_flutter_pdfviewer: ^26.2.14
  
  webview_flutter: ^4.9.0
  #https://pub.dev/packages/photo_view
  photo_view: ^0.15.0
  #https://pub.dev/packages/yandex_mapkit
  yandex_mapkit: ^4.1.0
  #https://pub.dev/packages/equatable
  equatable: ^2.0.5
  #https://pub.dev/packages/permission_handler
  permission_handler: ^11.3.1
  #https://pub.dev/packages/internet_connection_checker_plus
  internet_connection_checker_plus: ^2.7.0

  #https://pub.dev/packages/share_plus
  share_plus: ^10.1.0
  #https://pub.dev/packages/app_links
  app_links: ^6.3.3
  #https://pub.dev/packages/zoom_widget
  zoom_widget: ^2.0.1


  #https://pub.dev/packages/firebase_core
  firebase_core: ^3.0.0
  #https://pub.dev/packages/firebase_messaging
  firebase_messaging: ^15.1.3


  #https://pub.dev/packages/video_player
  video_player: ^2.9.2
  #https://pub.dev/packages/youtube_player_flutter
  youtube_player_flutter: ^9.1.1


  #https://pub.dev/packages/flutter_widget_from_html
  flutter_widget_from_html: ^0.15.3

  #todo note: upgrade flutter to 3.27
  #override flutter_widget_from_html package version
  chewie: 1.8.5


  #https://pub.dev/packages/url_launcher
  url_launcher: ^6.3.1
  #https://pub.dev/packages/package_info_plus
  package_info_plus: ^8.1.0
  #https://pub.dev/packages/in_app_update
  in_app_update: ^4.2.3
  #https://pub.dev/packages/flutter_upgrade_version
  flutter_upgrade_version: ^1.1.7
  #https://pub.dev/packages/connectivity_plus
  connectivity_plus: ^6.1.1
  #https://pub.dev/packages/dynamic_height_grid_view
  dynamic_height_grid_view: ^0.0.4
  #https://pub.dev/packages/appmetrica_push_plugin
  appmetrica_push_plugin: ^2.0.0
  #https://pub.dev/packages/appmetrica_plugin
  appmetrica_plugin: ^3.1.0
  #https://pub.dev/packages/animated_text_kit
  animated_text_kit: ^4.2.2
  #https://pub.dev/packages/inview_notifier_list
  inview_notifier_list: ^3.0.0
  #https://pub.dev/packages/visibility_detector
  visibility_detector: ^0.4.0+2
  #https://pub.dev/packages/flutter_swipe_detector
  flutter_swipe_detector: ^2.0.0
  #https://pub.dev/packages/better_player
  better_player: ^0.0.84
  #https://pub.dev/packages/shimmer
  shimmer: ^3.0.0
  freezed: ^2.5.7
  freezed_annotation: any

  shared_preferences: ^2.3.2
  qr_flutter: ^4.1.0
  dio: ^5.7.0
  geolocator: ^13.0.2
  hive: ^2.2.3
  device_info_plus: ^10.1.2
  internet_connection_checker: ^1.0.0+1
  dartz: ^0.10.1
  flex_color_scheme: ^7.3.1
  flutter_secure_storage: ^9.2.2
  image_picker: ^1.1.2


  modal_bottom_sheet:
    git:
      url: https://github.com/agym-co/modal_bottom_sheet.git
      ref: fix-status-bar-color-in-cupertino-modal-bottom-sheet-route
      path: modal_bottom_sheet


  flutter_json: ^0.0.4
  multi_long_press_gesture_recognizer: ^0.0.2
  split_view: ^3.2.1
  flutter_local_notifications: ^17.2.3
  linkify: ^5.0.0
  auto_size_text: ^3.0.0
  flutter_scale_tap: ^1.0.5
  animated_toggle_switch: ^0.8.3
  jiffy: ^6.3.2
  fluttertoast: ^8.2.8
  json_annotation: ^4.9.0
  hive_generator: ^2.0.1
  firebase_analytics: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  #https://pub.dev/packages/flutter_lints
  flutter_lints: ^5.0.0
  #https://pub.dev/packages/auto_route_generator
  auto_route_generator: ^9.0.0
  #https://pub.dev/packages/build_runner
  build_runner: ^2.4.13
  #https://pub.dev/packages/flutter_gen_runner
  flutter_gen_runner: ^5.8.0
  analyzer: ^6.2.0
  json_serializable: ^6.8.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/images/optic.png
    - assets/images/optic_carrera.png
    - assets/images/department_store.png
    - assets/images/
    - assets/images_external/
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/icons/reaction/
    - assets/icons/integrations/
    - assets/images/flag/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto-Light
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
    - family: Roboto-Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Graphik-Thin
      fonts:
        - asset: assets/fonts/Graphik-Thin.ttf
    - family: Graphik-Light
      fonts:
        - asset: assets/fonts/Graphik-Light.ttf
    - family: Graphik-Bold
      fonts:
        - asset: assets/fonts/Graphik-Bold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_intl:
  enabled: false
  main_locale: ru #Дефолтный язык приложения, если локаль не была найдена
  class_name: AppLocalization
  arb_dir: lib/localization/l10n/
  output_dir: lib/localization/l10n/generated
