name: services
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.3
  get_it: ^7.6.4
  models:
    path: ../models
  api_models:
    path: ../api_models


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
