name: ui_kit
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  google_fonts: ^4.0.4
  url_launcher: ^6.2.2
  qr_flutter: ^4.1.0
  # firebase_messaging: ^15.1.0
  firebase_core: ^3.9.0
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  models:
    path: ../models
  blocs:
    path: ../blocs
  shared:
    path: ../shared
  blind_chicken:
    path: ../../
  appmetrica_plugin: ^3.1.0
  photo_view: ^0.14.0
  video_player: ^2.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
