name: blocs
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.4.1
  internet_connection_checker_plus: ^2.2.0
  connectivity_plus: ^5.0.2
  json_annotation: ^4.8.1
  yandex_mapkit: ^4.1.0
  shared:
    path: ../shared
  repositories:
    path: ../repositories
  models:
    path: ../models
  ui_kit:
    path: ../ui_kit
  package_info_plus: ^8.0.2
  firebase_messaging: ^14.9.2
  appmetrica_plugin: ^3.0.0
  appmetrica_push_plugin: ^2.0.0
  decimal: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  freezed: ^2.4.5
