import 'package:blind_chicken/old_repos/models/models.dart';

class ConstatntsInfo {
  Map<String, String> listSort = {
    'n': 'Сначала новинки',
    'pd': 'По убыванию цены',
    'pu': 'По возрастанию цены',
  };

  List<String> months = [
    'января',
    'февраля',
    'марта',
    'апреля',
    'мая',
    'июня',
    'июля',
    'августа',
    'сентября',
    'октября',
    'ноября',
    'декабря',
  ];

  List<String> monthsDA = [
    'Январь',
    'Февраль',
    'Марта',
    'Апрель',
    'Май',
    'Июнь',
    'Июль',
    'Август',
    'Сентябрь',
    'Октябрь',
    'Ноябрь',
    'Декабрь',
  ];

  List<String> weekdayShrot = [
    'Пн',
    'Вт',
    'Ср',
    'Чт',
    'Пт',
    'Сб',
    'Вс',
  ];

  List<String> brandsWoman = [
    '3JUIN',
    'A Better Mistake',
    'Act N°1',
    'Actualee',
    'Aeron',
    'Agnona',
    'Alberta Ferretti',
    'Alevi',
    'Alexander McQueen',
    'Alexandre Vauthier',
    'Andrea Ventura',
    'Aqua di Parma',
    'Arizona Love',
    'Arma',
    'Art Dealer',
    'Balenciaga',
    'Barton Perreira',
    'Benedetta Bruzziches',
    'Blaze Milano',
    'Boss',
    'Bottega Veneta',
    'Burberry',
    'Bvlgari',
    'By Far',
    'Carolina Herrera',
    'Carrera',
    'Casadei',
    'Celine',
    'Chanel',
    'Charriol',
    'Chloe',
    'D.A.T.E.',
    'Daname',
    'Diesel',
    'Dior',
    'Disop',
    'Dita',
    'Dolce&Gabbana',
    'Dsquared2',
    'Dunhill',
    'Duvetica',
    'Eera',
    'Elie Saab',
    'Emporio Armani',
    'Erika Cavallini',
    'Estee Lauder',
    'Ex Nihilo',
    'Faith Connexion',
    'Fendi',
    'Filippo De Laurentiis',
    'Forte Forte',
    'Frederic Malle',
    'Furla',
    'GCDS',
    'Gia Borghini',
    'Giorgio Armani',
    'Givenchy',
    'Glory',
    'Gucci',
    'Guerlain',
    'Guess',
    'Haffmans&Neumeister',
    'Hermes',
    'Hibourama',
    'Hugo',
    'IC Berlin',
    'IRO',
    'Isabel Marant',
    'Ivy Oak',
    'Jimmy Choo',
    'Jo Malone',
    'Khaite',
    'Kilian',
    'Ksubi',
    'Le Silla',
    'Leisure Society',
    'Levi’s',
    'Linda Farrow',
    'Loewe',
    'Louis XIV',
    'Lunor',
    'LVIR',
    'Lyia',
    'Manebi',
    'Marc Jacobs',
    'Margaux Lonnberg',
    'Matsuda',
    'Max Mara',
    'MC2 Saint Barth',
    'Megapolis',
    'Michael Kors',
    'Miru',
    'Misho',
    'Missoni',
    'MM6 Maison Margiela',
    'Moncler',
    'MSGM',
    'MVP Wardrobe',
    'N°21',
    'Narciso Rodriguez',
    'Nivose',
    'Norma Kamali',
    'Oakley',
    'Oliver Peoples',
    'Orgreen',
    'Osoi',
    'P.A.R.O.S.H.',
    'Paco Rabanne',
    'Palto',
    'Paris Texas',
    'Pence',
    'Persol',
    'Philipp Plein',
    'Philipp Plein Sport',
    'Philippe Model',
    'Philosophy Di Lorenzo Serafini',
    'Polaroid',
    'Prada',
    'Premio',
    'Ray-Ban',
    'Re/Done',
    'Ricagno',
    'Saint Laurent',
    'Salvatore Santoro',
    'Saphir',
    'Seventh Street',
    'Shiseido',
    'Si Rossi by Sergio Rossi',
    'Sisley',
    'Smith',
    'Sonora',
    'Ssheena',
    'Stax',
    'Stella McCartney',
    'Tagliatore',
    'The Andamane',
    'Themoire',
    'Thom Browne',
    'Tiffany',
    'Tod’s',
    'Tom Ford',
    'Tramontano',
    'Valentino',
    'Versace',
    'Vogue',
    'Wolford',
    'Yohji Yamamoto',
    'Yuzefi',
  ];

  List<String> brandsMan = [
    '7 For All Mankind',
    'A Better Mistake',
    'Abla by Sartorio',
    'Agnona',
    'Alchemist',
    'Alexander McQueen',
    'Andrea Ventura',
    'Armani Exchange',
    'Balenciaga',
    'Barba Napoli',
    'Barrett',
    'Barton Perreira',
    'Berluti',
    'Bikkembergs',
    'Boss',
    'Bottega Veneta',
    'Brioni',
    'Brunello Cucinelli',
    'Burberry',
    'Bvlgari',
    'Carrera',
    'Chanel',
    'Charriol',
    'Corneliani',
    'D.A.T.E.',
    'David Beckham',
    'Diesel',
    'Dior',
    'Disop',
    'Dita',
    'Dolce&Gabbana',
    'Doucals',
    'Dsquared2',
    'Dunhill',
    'Duvetica',
    'Emporio Armani',
    'Ex Nihilo',
    'Fefe Napoli',
    'Fendi',
    'Filippo De Laurentiis',
    'Frederic Malle',
    'GCDS',
    'Giorgio Armani',
    'Givenchy',
    'Glory',
    'Gucci',
    'Guess',
    'Haffmans&Neumeister',
    'Hugo',
    'IC Berlin',
    'IH NOM UH NIT',
    'Isabel Benenato',
    'Jean Paul Gaultier',
    'Jimmy Choo',
    'Jo Malone',
    'Kilian',
    'Kired',
    'Ksubi',
    'Lardini',
    'Leisure Society',
    'Levi’s',
    'Linda Farrow',
    'Loewe',
    'Louis XIV',
    'Lunor',
    'Matsuda',
    'Maybach',
    'MC2 Saint Barth',
    'Megapolis',
    'Miru',
    'Missoni',
    'MM6 Maison Margiela',
    'Montblanc',
    'MSGM',
    'Narciso Rodriguez',
    'Nivose',
    'Oakley',
    'Oliver Peoples',
    'Paco Rabanne'
        'Pence',
    'Perofil',
    'Persol',
    'Peserico',
    'Philipp Plein',
    'Philipp Plein Sport',
    'Philippe Model',
    'Piacenza Cashmere',
    'Polaroid',
    'Prada',
    'Premio',
    'Ray-Ban',
    'Run of',
    'Saint Laurent',
    'Saphir',
    'Seventh Street',
    'Sisley',
    'Smith',
    'Stax',
    'Svevo Parma',
    'Thom Browne',
    'Tiffany',
    'Tod`s',
    'Tom Ford',
    'Tramontano',
    'Valentino',
    'Versace',
    'Yohji Yamamoto',
    'Zilli',
  ];

  List<String> brandsChilren = [
    'Aspesi',
    'Boss',
    'Carrera',
    'Chloe',
    'Diesel',
    'Dsquared2',
    'Glory',
    'Guess',
    'Marni',
    'MM6 Maison Margiela',
    'N°21',
    'Polaroid',
    'Ray-Ban',
    'Safilo',
    'Seventh Street',
    'Vogue',
  ];

  List<MainCategoryModel> categoryWoman = const [
    MainCategoryModel(
      title: 'Оптика',
      imagePath: 'optics_woman',
      pathMenu: '/optika/',
    ),
    MainCategoryModel(
      title: 'Обувь',
      imagePath: 'footwear_woman',
      pathMenu: '/obuv/',
    ),
    MainCategoryModel(
      title: 'Одежда',
      imagePath: 'clothes_woman',
      pathMenu: '/odezhda/',
    ),
    MainCategoryModel(
      title: 'Сумки',
      imagePath: 'bags_woman',
      pathMenu: '/sumki/',
    ),
    MainCategoryModel(
      title: 'Аксессуары',
      imagePath: 'accessories_woman',
      pathMenu: '/aksessuary/',
    ),
    MainCategoryModel(
      title: 'Косметика',
      imagePath: 'cosmetics_woman',
      pathMenu: '/kosmetika/',
    ),
    MainCategoryModel(
      title: 'Подарочная карта',
      imagePath: 'giftcard',
      pathMenu: '',
    ),
    MainCategoryModel(
      title: 'Проверка зрения',
      imagePath: 'vision',
      pathMenu: '',
    ),
    MainCategoryModel(
      title: 'Специальные предложения',
      imagePath: 'sale',
      pathMenu: '',
    ),
  ];

  List<MainCategoryModel> categoryMan = const [
    MainCategoryModel(
      title: 'Оптика',
      imagePath: 'optics_man',
      pathMenu: '/muzhchinam/optika/',
    ),
    MainCategoryModel(
      title: 'Обувь',
      imagePath: 'footwear_man',
      pathMenu: '/muzhchinam/obuv/',
    ),
    MainCategoryModel(
      title: 'Одежда',
      imagePath: 'clothes_man',
      pathMenu: '/muzhchinam/odezhda/',
    ),
    MainCategoryModel(
      title: 'Сумки',
      imagePath: 'bags_man',
      pathMenu: '/muzhchinam/sumki/',
    ),
    MainCategoryModel(
      title: 'Аксессуары',
      imagePath: 'accessories_man',
      pathMenu: '/muzhchinam/aksessuary/',
    ),
    MainCategoryModel(
      title: 'Косметика',
      imagePath: 'cosmetics_man',
      pathMenu: '/muzhchinam/kosmetika/',
    ),
    MainCategoryModel(
      title: 'Подарочная карта',
      imagePath: 'giftcard',
      pathMenu: '',
    ),
    MainCategoryModel(
      title: 'Проверка зрения',
      imagePath: 'vision_m',
      pathMenu: '',
    ),
    MainCategoryModel(
      title: 'Специальные предложения',
      imagePath: 'sale',
      pathMenu: '',
    ),
  ];

  List<MainCategoryModel> categoryChild = const [
    MainCategoryModel(
      title: 'Оптика',
      imagePath: 'optics_child',
      pathMenu: '/detyam/optika/',
    ),
    MainCategoryModel(
      title: 'Для девочек',
      imagePath: 'for_girls',
      pathMenu: '/detyam/odezhda-dlya-devochek/',
    ),
    MainCategoryModel(
      title: 'Для мальчиков',
      imagePath: 'for_boys',
      pathMenu: '/detyam/odezhda-dlya-malchikov/',
    ),
    MainCategoryModel(
      title: 'Сумки',
      imagePath: 'bags_child',
      pathMenu: '/detyam/sumki/',
    ),
    MainCategoryModel(
      title: 'Аксессуары',
      imagePath: 'accessories_child',
      pathMenu: '/detyam/aksessuary/',
    ),
    MainCategoryModel(
      title: 'Для малышей',
      imagePath: 'for_child',
      pathMenu: '/detyam/dlya-malyshey/',
    ),
    MainCategoryModel(
      title: 'Подарочная карта',
      imagePath: 'giftcard',
      pathMenu: '',
    ),
    MainCategoryModel(
      title: 'Проверка зрения',
      imagePath: 'vision_c',
      pathMenu: '',
    ),
    MainCategoryModel(
      title: 'Специальные предложения',
      imagePath: 'sale',
      pathMenu: '',
    ),
  ];

  List<String> listAlphabetAndNumber = [
    '0-9',
    'A',
    'B',
    'C',
    'D',
    'E',
    'F',
    'G',
    'H',
    'I',
    'J',
    'K',
    'L',
    'M',
    'N',
    'O',
    'P',
    'R',
    'S',
    'T',
    'V',
    'W',
    'Y',
    'Z',
  ];

  List<ContentInfoItemDataModel> home = [
    ContentInfoItemDataModel(
      id: '0',
      title: 'Женщинам',
      mobileImage: 'woman',
      tabletImage: '',
      url: '/zhenshchinam/',
    ),
    ContentInfoItemDataModel(
      id: '1',
      title: 'Мужчинам',
      mobileImage: 'man',
      tabletImage: '',
      url: '/muzhchinam/',
    ),
    ContentInfoItemDataModel(
      id: '2',
      title: 'Детям',
      mobileImage: 'child',
      tabletImage: '',
      url: '/detyam/',
    ),
    ContentInfoItemDataModel(
      id: '3',
      title: 'Подарочная карта',
      mobileImage: 'giftcard',
      tabletImage: 'giftcard_f',
      url: '/giftcard/',
    ),
    ContentInfoItemDataModel(
      id: '4',
      title: 'Проверка зрения',
      mobileImage: 'vision',
      tabletImage: 'vision_f',
      url: '/proverka-zreniya/',
    ),
    ContentInfoItemDataModel(
      id: '5',
      title: 'Спецпредложения',
      mobileImage: 'sale',
      tabletImage: 'sale_f',
      url: '/sale/',
    ),
    ContentInfoItemDataModel(
      id: '6',
      title: 'Бренды',
      mobileImage: 'brands',
      tabletImage: 'brands_f',
      url: '/brands/',
    ),
  ];

  List<ContentInfoItemDataModel> women = [
    ContentInfoItemDataModel(
      id: '0',
      title: 'Оптика',
      mobileImage: 'optics_woman',
      tabletImage: 'optics_woman',
      url: '/optika/',
    ),
    ContentInfoItemDataModel(
      id: '1',
      title: 'Обувь',
      mobileImage: 'footwear_woman',
      tabletImage: 'footwear_woman',
      url: '/obuv/',
    ),
    ContentInfoItemDataModel(
      id: '2',
      title: 'Одежда',
      mobileImage: 'clothes_woman',
      tabletImage: 'clothes_woman',
      url: '/odezhda/',
    ),
    ContentInfoItemDataModel(
      id: '3',
      title: 'Сумки',
      mobileImage: 'bags_woman',
      tabletImage: 'bags_woman',
      url: '/sumki/',
    ),
    ContentInfoItemDataModel(
      id: '4',
      title: 'Аксессуары',
      mobileImage: 'accessories_woman',
      tabletImage: 'accessories_woman',
      url: '/aksessuary/',
    ),
    ContentInfoItemDataModel(
      id: '5',
      title: 'Косметика',
      mobileImage: 'cosmetics_woman',
      tabletImage: 'cosmetics_woman',
      url: '/kosmetika/',
    ),
    ContentInfoItemDataModel(
      id: '6',
      title: 'Подарочная карта',
      mobileImage: 'giftcard',
      tabletImage: 'giftcard_f',
      url: '/giftcard/',
    ),
    ContentInfoItemDataModel(
      id: '7',
      title: 'Проверка зрения',
      mobileImage: 'vision',
      tabletImage: 'vision_f',
      url: '/proverka-zreniya/',
    ),
    ContentInfoItemDataModel(
      id: '8',
      title: 'Спецпредложения',
      mobileImage: 'sale',
      tabletImage: 'sale_f',
      url: '/sale/zhenshchinam/',
    ),
    ContentInfoItemDataModel(
      id: '9',
      title: 'Бренды',
      mobileImage: 'brands',
      tabletImage: 'brands_f',
      url: '/brands/zhenshchinam/',
    ),
  ];

  List<ContentInfoItemDataModel> men = [
    ContentInfoItemDataModel(
      id: '0',
      title: 'Оптика',
      mobileImage: 'optics_man',
      tabletImage: 'optics_man',
      url: '/muzhchinam/optika/',
    ),
    ContentInfoItemDataModel(
      id: '1',
      title: 'Обувь',
      mobileImage: 'footwear_man',
      tabletImage: 'footwear_man',
      url: '/muzhchinam/obuv/',
    ),
    ContentInfoItemDataModel(
      id: '2',
      title: 'Одежда',
      mobileImage: 'clothes_man',
      tabletImage: 'clothes_man',
      url: '/muzhchinam/odezhda/',
    ),
    ContentInfoItemDataModel(
      id: '3',
      title: 'Сумки',
      mobileImage: 'bags_man',
      tabletImage: 'bags_man',
      url: '/muzhchinam/sumki/',
    ),
    ContentInfoItemDataModel(
      id: '4',
      title: 'Аксессуары',
      mobileImage: 'accessories_man',
      tabletImage: 'accessories_man',
      url: '/muzhchinam/aksessuary/',
    ),
    ContentInfoItemDataModel(
      id: '5',
      title: 'Косметика',
      mobileImage: 'cosmetics_man',
      tabletImage: 'cosmetics_man',
      url: '/muzhchinam/kosmetika/',
    ),
    ContentInfoItemDataModel(
      id: '6',
      title: 'Подарочная карта',
      mobileImage: 'giftcard',
      tabletImage: 'giftcard_f',
      url: '/giftcard/',
    ),
    ContentInfoItemDataModel(
      id: '7',
      title: 'Проверка зрения',
      mobileImage: 'vision_m',
      tabletImage: 'vision_m_f',
      url: '/proverka-zreniya/',
    ),
    ContentInfoItemDataModel(
      id: '8',
      title: 'Спецпредложения',
      mobileImage: 'sale',
      tabletImage: 'sale_f',
      url: '/sale/muzhchinam/',
    ),
    ContentInfoItemDataModel(
      id: '9',
      title: 'Бренды',
      mobileImage: 'brands',
      tabletImage: 'brands_f',
      url: '/brands/muzhchinam/',
    ),
  ];

  List<ContentInfoItemDataModel> children = [
    ContentInfoItemDataModel(
      id: '0',
      title: 'Оптика',
      mobileImage: 'optics_child',
      tabletImage: 'optics_child',
      url: '/detyam/optika/',
    ),
    ContentInfoItemDataModel(
      id: '1',
      title: 'Для девочек',
      mobileImage: 'for_girls',
      tabletImage: 'for_girls',
      url: '/detyam/odezhda-dlya-devochek/',
    ),
    ContentInfoItemDataModel(
      id: '2',
      title: 'Для мальчиков',
      mobileImage: 'for_boys',
      tabletImage: 'for_boys',
      url: '/detyam/odezhda-dlya-malchikov/',
    ),
    ContentInfoItemDataModel(
      id: '3',
      title: 'Сумки',
      mobileImage: 'bags_child',
      tabletImage: 'bags_child',
      url: '/detyam/sumki/',
    ),
    ContentInfoItemDataModel(
      id: '4',
      title: 'Аксессуары',
      mobileImage: 'accessories_child',
      tabletImage: 'accessories_child',
      url: '/detyam/aksessuary/',
    ),
    ContentInfoItemDataModel(
      id: '5',
      title: 'Для малышей',
      mobileImage: 'for_child',
      tabletImage: 'for_child',
      url: '/detyam/dlya-malyshey/',
    ),
    ContentInfoItemDataModel(
      id: '6',
      title: 'Подарочная карта',
      mobileImage: 'giftcard',
      tabletImage: 'giftcard_f',
      url: '/giftcard/',
    ),
    ContentInfoItemDataModel(
      id: '7',
      title: 'Проверка зрения',
      mobileImage: 'vision_c',
      tabletImage: 'vision_c_f',
      url: '/proverka-zreniya/',
    ),
    ContentInfoItemDataModel(
      id: '8',
      title: 'Спецпредложения',
      mobileImage: 'sale',
      tabletImage: 'sale_f',
      url: '/sale/detyam/',
    ),
    ContentInfoItemDataModel(
      id: '9',
      title: 'Бренды',
      mobileImage: 'brands',
      tabletImage: 'brands_f',
      url: '/brands/detyam/',
    ),
  ];
}
